; timining-critical flipping of top border colours
; 224 t-states per row
TOP_BORDER_RENDER:		

	; can't trash registers...
	PUSH 	AF 
	PUSH 	BC
	PUSH	HL

	LD		C, $FE
	LD 		HL, TOP_BORDER_BUFFER

	LD 		B, 56		; 56 top border without contention
TOP_BORDER_RENDER_LOOP:	
	;11 cols
	LD 		A, B

	OUTI	
	OUTI	
	OUTI	
	OUTI	

	OUTI	
	OUTI	
	OUTI	
	OUTI	

	OUTI	
	OUTI	
	OUTI	

	; hblank & timing desu...
	.5 NOP
	LD  	B, A
	LD 		A, (HL)

	DJNZ    TOP_BORDER_RENDER_LOOP

;	LD  	A, 0		; back to black border
	LD 		A, 4		; green for timings debug...
	OUT		($FE), A

	; can't trash reg
	POP 	HL
	POP 	BC 
	POP 	AF 

	JP		TOP_BORDER_RENDER_OVER

; 56 x 11
TOP_BORDER_BUFFER:
	DEFS 	11, COL_WHT
	DEFS 	11, COL_WHT
	DEFS 	11, COL_WHT
	DEFS 	11, COL_WHT
	DEFS 	11, COL_WHT
	DEFS 	11, COL_WHT
	DEFS 	11, COL_WHT
	DEFS 	11, COL_BLK

	DEFS 	11, COL_WHT
	DEFS 	11, COL_WHT
	DEFS 	11, COL_WHT
	DEFS 	11, COL_WHT
	DEFS 	11, COL_WHT
	DEFS 	11, COL_WHT
	DEFS 	11, COL_BLK
	DEFS 	11, COL_BLK

	DEFS 	11, COL_WHT
	DEFS 	11, COL_WHT
	DEFS 	11, COL_WHT
	DEFS 	11, COL_WHT
	DEFS 	11, COL_WHT
	DEFS 	11, COL_BLK
	DEFS 	11, COL_BLK
	DEFS 	11, COL_BLK

	DEFS 	11, COL_WHT
	DEFS 	11, COL_WHT
	DEFS 	11, COL_WHT
	DEFS 	11, COL_WHT
	DEFS 	11, COL_BLK
	DEFS 	11, COL_BLK
	DEFS 	11, COL_BLK
	DEFS 	11, COL_BLK

	DEFS 	11, COL_WHT
	DEFS 	11, COL_WHT
	DEFS 	11, COL_WHT
	DEFS 	11, COL_BLK
	DEFS 	11, COL_BLK
	DEFS 	11, COL_BLK
	DEFS 	11, COL_BLK
	DEFS 	11, COL_BLK

	DEFS 	11, COL_WHT
	DEFS 	11, COL_WHT
	DEFS 	11, COL_BLK
	DEFS 	11, COL_BLK
	DEFS 	11, COL_BLK
	DEFS 	11, COL_BLK
	DEFS 	11, COL_BLK
	DEFS 	11, COL_BLK

	DEFB 	COL_BLK, COL_WHT, COL_WHT, COL_WHT, COL_WHT, COL_WHT, COL_WHT, COL_WHT, COL_WHT, COL_WHT, COL_BLK
	DEFS 	11, COL_BLK
	DEFS 	11, COL_BLK
	DEFS 	11, COL_BLK
	DEFS 	11, COL_BLK
	DEFS 	11, COL_BLK
	DEFS 	11, COL_BLK
	DEFS 	11, COL_BLK

